server:
  port: 9100
spring:
  application:
    name: eureka-member
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka
    register-with-eureka: true
    fetch-registry: true

